<?php
declare(strict_types=1);

/** @version 1.1.0 */

use Loki\CssUtils\Util\CssClass;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var CssClass $css */
/** @var Escaper $escaper */

$tabName = $block->getTabName();
$tabLabel = $block->getTabLabel();
?>
<div>
    <button
        role="tab"
        aria-controls="tab-<?= $escaper->escapeHtml($tabName) ?>"
        data-tab-name="<?= $escaper->escapeHtml($tabName) ?>"
        type="button"
        @click.prevent="switchTab"
        :class="buttonCssClass">
        <?= $escaper->escapeHtml(__($tabLabel)) ?>
    </button>
</div>
