<?php
declare(strict_types=1);

/** @version 1.1.0 */

use Loki\CssUtils\Util\CssClass;
use Loki\Debugger\Component\Debugger\DebuggerViewModel;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var CssClass $css */
/** @var Escaper $escaper */
/** @var DebuggerViewModel $viewModel */

$viewModel = $block->getAncestorBlock()->getViewModel();
?>
<div :class="tabCssClass" class="<?= $escaper->escapeHtml($css('p-4')) ?>" data-tab-name="server-dump" id="tab-server-dump">
    <h3 class="<?= $escaper->escapeHtml($css('text-xl my-4', 'tab-heading')) ?>">
        <?= $escaper->escapeHtml(__('Server Dump')) ?>
    </h3>
    <pre><?php var_dump($viewModel->getData()) ?></pre>
</div>
