<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @version 1.1.1 */
/** @var Template $block */
?>
<script>
    document.addEventListener('alpine:init', () => {
        Alpine.directive('json', (el, { value, expression }, { evaluate }) => {
            if (expression) {
                el.textContent = JSON.stringify(evaluate(expression));
            }
        });
    });
</script>
