<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\LokiComponents\Util\IdConvertor;
use Yireo\LokiComponentsDebugger\Component\Debugger\DebuggerViewModel;
use Yireo\LokiComponents\Factory\ViewModelFactory;

/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var DebuggerViewModel $viewModel */
/** @var IdConvertor $idConvertor */

$idConvertor = $viewModelFactory->create(IdConvertor::class);
$htmlId = $idConvertor->toElementId($block->getNameInLayout());
?>
<div class="hidden md:block w-full border-t border-gray-400">
    <ul class="flex items-stretch overflow-x-auto" role="tablist">
        <li class="border-b border-gray-300 p-2">
            Loki Components Debugger
        </li>
        <li>
            <button
                data-tab-name="server"
                type="button"
                @click="switchTab"
                :class="buttonCssClass"
                class="inline-flex rounded-t-lg border-t border-l border-r p-4 border-gray-300 ">Server Dump
            </button>
        </li>
        <li>
            <button
                data-tab-name="components"
                type="button"
                @click="switchTab"
                :class="buttonCssClass"
                class="inline-flex rounded-t-lg border-t border-l border-r p-4 border-gray-300 ">Registered Components
            </button>
        </li>
    </ul>

    <div>
        <div role="tab" :class="tabCssClass" class="p-4" data-tab-name="server">
            <h3 class="text-xl my-4">Server Dump</h3>
            <pre><?php var_dump($viewModel->getData()) ?></pre>
        </div>

        <div role="tab" :class="tabCssClass" class="p-4"  data-tab-name="components">
            <table class="table-auto w-full text-xs">
                <thead>
                <tr>
                    <th class="border-b border-gray-300 p-2">Component ID</th>
                    <th class="border-b border-gray-300 p-2">Component name</th>
                    <th class="border-b border-gray-300 p-2">Element ID</th>
                    <th class="border-b border-gray-300 p-2">Block name</th>
                    <th class="border-b border-gray-300 p-2">Details</th>
                </tr>
                </thead>
                <tbody>
                <template x-for="component in components">
                    <tr>
                        <td class="border-b border-gray-300 p-2">
                            <code x-text="component.id"></code>
                        </td>
                        <td class="border-b border-gray-300 p-2">
                            <code x-text="component.name"></code>
                        </td>
                        <td class="border-b border-gray-300 p-2">
                            <code x-text="component.elementId"></code>
                        </td>
                        <td class="border-b border-gray-300 p-2">
                            <code x-text="component.blockId"></code>
                        </td>
                        <td class="border-b border-gray-300 p-2">
                            <code x-text="component.getDetailsString"></code>
                        </td>
                    </tr>
                </template>
                </tbody>
            </table>
        </div>
    </div>
</div>

