<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Loki\Components\Util\IdConvertor;
use Loki\Debugger\Component\Debugger\DebuggerViewModel;
use Loki\Components\Factory\ViewModelFactory;

/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var DebuggerViewModel $viewModel */
/** @var IdConvertor $idConvertor */

$idConvertor = $viewModelFactory->create(IdConvertor::class);
$htmlId = $idConvertor->toElementId($block->getNameInLayout());
?>
<div class="hidden md:block w-full border-t border-gray-400">
    <div class="flex items-stretch overflow-x-auto" role="tablist">
        <div class="border-b border-gray-300 p-2">
            <span role="tab">Loki Debugger</span>
        </div>
        <div>
            <button
                role="tab"
                aria-controls="tab-server"
                data-tab-name="server"
                type="button"
                @click="switchTab"
                :class="buttonCssClass"
                class="inline-flex rounded-t-lg border-t border-l border-r p-4 border-gray-300 ">
                Server Dump
            </button>
        </div>
        <div>
            <button
                role="tab"
                aria-controls="tab-components"
                data-tab-name="components"
                type="button"
                @click="switchTab"
                :class="buttonCssClass"
                class="inline-flex rounded-t-lg border-t border-l border-r p-4 border-gray-300 ">
                Registered Components
            </button>
        </div>
    </div>

    <div>
        <div :class="tabCssClass" class="p-4" data-tab-name="server" id="tab-server">
            <h3 class="text-xl my-4">Server Dump</h3>
            <pre><?php var_dump($viewModel->getData()) ?></pre>
        </div>

        <div :class="tabCssClass" class="p-4"  data-tab-name="components" id="tab-components">
            <table class="table-auto w-full text-xs">
                <thead>
                <tr>
                    <th class="border-b border-gray-300 p-2">Alpine Instance / Component</th>
                    <th class="border-b border-gray-300 p-2">Element ID</th>
                    <th class="border-b border-gray-300 p-2">Loki Component Name</th>
                    <th class="border-b border-gray-300 p-2">Value</th>
                    <th class="border-b border-gray-300 p-2">Details</th>
                </tr>
                </thead>
                <tbody>
                <template x-for="component in components" :key="component.id">
                    <tr>
                        <td class="border-b border-gray-300 p-2">
                            <strong><code x-text="component.id"></code></strong><br/>
                            <code x-text="component.name"></code>
                        </td>
                        <td class="border-b border-gray-300 p-2">
                            <code x-text="component.elementId"></code>
                        </td>
                        <td class="border-b border-gray-300 p-2">
                            <code x-text="component.blockId"></code>
                        </td>
                        <td class="border-b border-gray-300 p-2">
                            <code x-text="component.value"></code>
                        </td>
                        <td class="border-b border-gray-300 p-2">
                            <code x-json="component.getDetails"></code>
                        </td>
                    </tr>
                </template>
                </tbody>
            </table>
        </div>
    </div>
</div>

