<?php
declare(strict_types=1);

/** @version 1.0.5 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('LokiComponentsDebugger', () => ({
            ...LokiComponentType,
            currentTab: '',
            components: [],
            init() {
                this.loadComponents();

                this.currentTab = LokiComponentsStorage.load('debugger.tab');
                if (!this.currentTab) {
                    this.currentTab = this.$root.querySelectorAll('[data-tab-name]')[0].getAttribute('data-tab-name');
                }

                document.addEventListener('loki-components.component-register', () => {
                    this.loadComponents();
                })
            },
            reload() {
                this.loadComponents();
            },
            loadComponents() {
                try {
                    this.components = Alpine.store('components').getComponents();
                } catch (e) {
                }
            },
            isSelected(tabName) {
                return tabName === this.currentTab;
            },
            buttonCssClass() {
                const tabName = this.$el.getAttribute('data-tab-name');
                if (this.isSelected(tabName)) {
                    return 'border-transparent bg-white';
                }

                return 'border-gray-200 bg-zinc-200';
            },
            tabCssClass() {
                const tabName = this.$el.getAttribute('data-tab-name');
                if (this.isSelected(tabName)) {
                    return '';
                }

                return 'hidden';
            },
            switchTab(event) {
                this.currentTab = event.target.getAttribute('data-tab-name');
                LokiComponentsStorage.save('debugger.tab', this.currentTab);
                this.reload();
            }
        }));
    });
</script>

