<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @version 1.1.0 */
/** @var Template $block */
?>
<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('LokiComponentsDebugger', () => ({
            ...LokiComponentType,
            currentTab: '',
            components: [],
            visible: true,
            invisible() {
                return !this.visible;
            },
            init() {
                this.visible = parseInt(LokiComponentsStorage.load('debugger.visible')) === 1;
                const toolbarHeight = parseInt(LokiComponentsStorage.load('debugger.height')) || 100;
                if (toolbarHeight) {
                    this.$refs.toolbar.style.height = toolbarHeight + "px";
                }

                this.loadComponents();

                this.currentTab = LokiComponentsStorage.load('debugger.tab');
                if (!this.currentTab) {
                    const defaultTab = this.$root.querySelectorAll('[data-tab-name]')[0];
                    if (defaultTab) {
                        this.currentTab = defaultTab.getAttribute('data-tab-name');
                    }
                }

                document.addEventListener('loki-components.component-register', () => {
                    this.loadComponents();
                });

                let startY = 0;
                let startHeight = 0;
                this.$refs.resizer.addEventListener("mousedown", (e) => {
                    startY = e.clientY;
                    startHeight = this.$refs.toolbar.offsetHeight;

                    document.addEventListener("mousemove", onDrag);
                    document.addEventListener("mouseup", stopDrag);
                });

                const onDrag = (e) => {
                    const delta = e.clientY - startY;
                    const newHeight = startHeight - delta;
                    this.$refs.toolbar.style.height = newHeight + "px";
                    LokiComponentsStorage.save('debugger.height', newHeight);
                }

                const stopDrag = () => {
                    document.removeEventListener("mousemove", onDrag);
                    document.removeEventListener("mouseup", stopDrag);
                }
            },
            toggleVisibility() {
                this.visible = !this.visible;
                LokiComponentsStorage.save('debugger.visible', this.visible ? 1 : 0);
            },
            reload() {
                this.loadComponents();
            },
            loadComponents() {
                try {
                    this.components = Alpine.store('LokiComponents').getComponents();
                } catch (e) {
                }
            },
            isSelected(tabName) {
                return tabName === this.currentTab;
            },
            buttonCssClass() {
                const defaultCss = 'inline-flex rounded-t-lg border-t border-l border-r p-4';
                const tabName = this.$el.getAttribute('data-tab-name');
                if (this.isSelected(tabName)) {
                    return defaultCss + ' border-transparent bg-orange-50';
                }

                return defaultCss + ' border-transparent text-white';
            },
            tabCssClass() {
                const tabName = this.$el.getAttribute('data-tab-name');
                if (this.isSelected(tabName)) {
                    return '';
                }

                return 'hidden';
            },
            switchTab(event) {
                this.currentTab = event.target.getAttribute('data-tab-name');
                LokiComponentsStorage.save('debugger.tab', this.currentTab);
                this.reload();
            }
        }));
    });
</script>

